CREATE TABLE IF NOT EXISTS CATEGORY (
    CATEGORY_NAME VARCHAR(255) PRIMARY KEY,
    CATEGORY_TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SAVING_CATEGORY (
    ID_CATEGORY_SAVING VARCHAR(255) PRIMARY KEY,
    SAVING_NAME VARCHAR(255),
    MAX_OUTCOME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS DEPOSIT (
    ID_DEPOSIT VARCHAR(255) PRIMARY KEY,
    DEPOSIT_AMNT VARCHAR(255),
    CAT_EXPENSES VARCHAR(255),
    SAVING_TYPE VARCHAR(255),
    TRANSACTION_DATE DATE
);

CREATE TABLE IF NOT EXISTS WITHDRAW (
    ID_WITHDRAWAL VARCHAR(255) PRIMARY KEY,
    WITHDRAWAL_AMNT VARCHAR(255),
    CAT_EXPENSES VARCHAR(255),
    SAVING_TYPE VARCHAR(255),
    TRANSACTION_DATE DATE
);

CREATE TABLE IF NOT EXISTS SAVING_LOG (
    ID_TRANSACTION VARCHAR(255) PRIMARY KEY,
    TRANSACTION_TYPE VARCHAR(255),
    TRANSACTION_AMOUNT VARCHAR(255),
    TRANSACTION_CAT VARCHAR(255),
    TRANSACTION_DATE DATE,
    SAVING_TYPE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS CATEGORY_BUDGET (
    ID VARCHAR(255) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(255),
    BUDGET_LIMIT VARCHAR(255),
    CREATED_DATE DATE
);
